status = WARN
name = SparkLog4j2

appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_ERR

appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c: %m%n

rootLogger.level = INFO
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = console

# MicroBatchExecutionContext 로그 억제
logger.microBatchExecutionContext.name = org.apache.spark.sql.execution.streaming.MicroBatchExecutionContext
logger.microBatchExecutionContext.level = WARN

# Spark Connect - 2초마다 발생하는 세션 접근 로그 제거
logger.sessionHolder.name = org.apache.spark.sql.connect.service.SessionHolder
logger.sessionHolder.level = WARN


# 데이터가 없을 때 10초마다 발생하는 idle 로그 제거
logger.progressReporter.name = org.apache.spark.sql.execution.streaming.ProgressReporter
logger.progressReporter.level = WARN